<a href="https://colab.research.google.com/github/AbhishekShah272002/Deep-Learning-and-NLP/blob/main/Deep_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

print(torch.__version__)
print(torch.cuda.is_available())

2.11.0+cu128
True


In [6]:
# Creating Cpu example
first_tens = torch.tensor([1, 2, 3])
second_tens = torch.tensor([4,5,6])
print(first_tens)
print(second_tens)
add_tens = first_tens + second_tens
print(add_tens)

tensor([1, 2, 3])
tensor([4, 5, 6])
tensor([5, 7, 9])


In [7]:
sub_tens = first_tens - second_tens
print(sub_tens)
print(sub_tens.shape)

tensor([-3, -3, -3])
torch.Size([3])


In [15]:
# Creating Gpu example
if torch.cuda.is_available(): device = "cuda"
else: device = "cpu"
print(device)

cuda


In [16]:
tens_a = torch.tensor([1,2,3]).to(device)
tens_b = torch.tensor([4,5,6]).to(device)
add_tens = tens_a + tens_b
print(add_tens)

tensor([5, 7, 9], device='cuda:0')
