<a href="https://colab.research.google.com/github/AbhishekShah272002/Deep-Learning-and-NLP/blob/main/Deep_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch

print(torch.__version__)
print(torch.cuda.is_available())

2.11.0+cu128
True


In [4]:
# Creating Cpu example
first_tens = torch.tensor([1, 2, 3])
second_tens = torch.tensor([4,5,6])
print(first_tens)
print(second_tens)
add_tens = first_tens + second_tens
print(add_tens)

tensor([1, 2, 3])
tensor([4, 5, 6])
tensor([5, 7, 9])


In [41]:
first_tens.device

device(type='cpu')

In [42]:
first_tens.dtype

torch.int64

In [43]:
first_tens.shape

torch.Size([3])

In [44]:
first_tens.ndim

1

In [5]:
sub_tens = first_tens - second_tens
print(sub_tens)
print(sub_tens.shape)

tensor([-3, -3, -3])
torch.Size([3])


In [6]:
# Creating Gpu example
if torch.cuda.is_available(): device = "cuda"
else: device = "cpu"
print(device)

cuda


In [7]:
tens_a = torch.tensor([1,2,3]).to(device)
tens_b = torch.tensor([4,5,6]).to(device)
add_tens = tens_a + tens_b
print(add_tens)

tensor([5, 7, 9], device='cuda:0')


In [36]:
# Using torch.empty(), torch.ones(), and torch
empty_tens = torch.empty(2,3)
zero_tens = torch.zeros(2,3)
ones_tens = torch.ones(2,3)
print("empty_tens: ",empty_tens)
print("zero_tens ",zero_tens)
print("ones_tens ",ones_tens)

empty_tens:  tensor([[9.3240e-17, 0.0000e+00, 3.0413e+01],
        [4.5422e-41, 8.9683e-44, 0.0000e+00]])
zero_tens  tensor([[0., 0., 0.],
        [0., 0., 0.]])
ones_tens  tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [21]:
# Filled with random numbers from a uniform distribution
rand_un = torch.rand(2,2)
print(rand_un)
# Filled with random numbers from a normal distribution
rand_norm = torch.randn(2,2)
print(rand_norm)
# Filled with random integers generated uniformaly
rand_int = torch.randint(10,100,(2,2))
print(rand_int)

tensor([[0.9309, 0.4675],
        [0.5909, 0.7948]])
tensor([[0.1181, 0.8322],
        [0.7690, 0.1972]])
tensor([[28, 26],
        [48, 67]])
