<a href="https://colab.research.google.com/github/AbhishekShah272002/Deep-Learning-and-NLP/blob/main/Deep_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import torch

print(torch.__version__)
print(torch.cuda.is_available())

2.11.0+cu128
True


In [7]:
# Creating Cpu example
first_tens = torch.tensor([1, 2, 3])
second_tens = torch.tensor([4,5,6])
print(first_tens)
print(second_tens)
add_tens = first_tens + second_tens
print(add_tens)

tensor([1, 2, 3])
tensor([4, 5, 6])
tensor([5, 7, 9])


In [8]:
first_tens.device

device(type='cpu')

In [9]:
first_tens.dtype

torch.int64

In [10]:
first_tens.shape

torch.Size([3])

In [11]:
first_tens.ndim

1

In [12]:
sub_tens = first_tens - second_tens
print(sub_tens)
print(sub_tens.shape)

tensor([-3, -3, -3])
torch.Size([3])


In [13]:
# Creating Gpu example
if torch.cuda.is_available(): device = "cuda"
else: device = "cpu"
print(device)

cuda


In [14]:
tens_a = torch.tensor([1,2,3]).to(device)
tens_b = torch.tensor([4,5,6]).to(device)
add_tens = tens_a + tens_b
print(add_tens)

tensor([5, 7, 9], device='cuda:0')


In [15]:
# Using torch.empty(), torch.ones(), and torch
empty_tens = torch.empty(2,3)
zero_tens = torch.zeros(2,3)
ones_tens = torch.ones(2,3)
print("empty_tens: ",empty_tens)
print("zero_tens ",zero_tens)
print("ones_tens ",ones_tens)

empty_tens:  tensor([[1.5766e-19, 1.0256e-08, 1.0501e-05],
        [3.1644e+12, 2.7098e-09, 2.6707e-06]])
zero_tens  tensor([[0., 0., 0.],
        [0., 0., 0.]])
ones_tens  tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [16]:
# Filled with random numbers from a uniform distribution
rand_un = torch.rand(2,2)
print(rand_un)
# Filled with random numbers from a normal distribution
rand_norm = torch.randn(2,2)
print(rand_norm)
# Filled with random integers generated uniformaly
rand_int = torch.randint(10,100,(2,2))
print(rand_int)

tensor([[0.3668, 0.7484],
        [0.5914, 0.6519]])
tensor([[ 0.3574,  0.5928],
        [ 0.4348, -1.2650]])
tensor([[66, 94],
        [54, 25]])


In [17]:
starting_tensor = torch.ones(2, 3) # Example: Define a starting tensor
# Tensor with the same size filled with randon numbers
torch.manual_seed(111)
rand_tens = torch.rand_like(starting_tensor)
rand_tens

tensor([[0.7156, 0.9140, 0.2819],
        [0.2581, 0.6311, 0.6001]])

In [18]:
torch.full_like(starting_tensor,7)

tensor([[7., 7., 7.],
        [7., 7., 7.]])

In [24]:
# Indexing 1-dim tensor example
one_dim_tensor = torch.tensor([1,2,3,4,5])
print(one_dim_tensor)
print(one_dim_tensor[2])
print(one_dim_tensor[2].item())

tensor([1, 2, 3, 4, 5])
tensor(3)
3


In [33]:
# Slicing example
dim = torch.tensor([1,2,3,4,5,6])
print(dim[1:4])
print(dim<5)

tensor([2, 3, 4])
tensor([ True,  True,  True,  True, False, False])
