<a href="https://colab.research.google.com/github/AbhishekShah272002/Deep-Learning-and-NLP/blob/main/Deep_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

print(torch.__version__)
print(torch.cuda.is_available())

2.11.0+cu128
True


In [6]:
first_tens = torch.tensor([1, 2, 3])
second_tens = torch.tensor([4,5,6])
print(first_tens)
print(second_tens)
add_tens = first_tens + second_tens
print(add_tens)

tensor([1, 2, 3])
tensor([4, 5, 6])
tensor([5, 7, 9])
